#!/bin/bash

# BreachAR - GitHub Actions Setup Script
# Execute: bash scripts/setup-github-actions.sh

echo "=================================="
echo "  BreachAR - GitHub Actions Setup"
echo "=================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo -e "${RED}Git is not installed. Please install git first.${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Git found${NC}"

# Check if we're in the project directory
if [ ! -f "00_readme.md" ]; then
    echo -e "${YELLOW}Warning: Not in BreachAR project directory${NC}"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Initialize git if not already initialized
if [ ! -d ".git" ]; then
    echo -e "${YELLOW}Initializing git repository...${NC}"
    git init
    echo -e "${GREEN}✓ Git initialized${NC}"
fi

# Create .gitignore if not exists
if [ ! -f ".gitignore" ]; then
    echo -e "${YELLOW}Creating .gitignore...${NC}"
    cat > .gitignore << 'EOF'
# Unity generated
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# MemoryCaptures
/[Mm]emoryCaptures/

# Recordings
/[Rr]ecordings/

# Asset meta data should only be ignored when the corresponding asset is also ignored
!/[Aa]ssets/**/*.meta

# Autogenerated Coverage
/[Cc]overage/

# Autogenerated VS/MD/Rider solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.app

# Crashlytics generated file
crashlytics-build.properties

# OS generated
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# Gradle (Android)
.gradle/
local.properties
*.keystore
!debug.keystore
EOF
    echo -e "${GREEN}✓ .gitignore created${NC}"
fi

# Stage all files
echo -e "${YELLOW}Staging files...${NC}"
git add .
echo -e "${GREEN}✓ Files staged${NC}"

# Initial commit
echo -e "${YELLOW}Creating initial commit...${NC}"
git commit -m "Initial commit: BreachAR project setup"
echo -e "${GREEN}✓ Initial commit created${NC}"

# Instructions
echo ""
echo "=================================="
echo "  Next Steps:"
echo "=================================="
echo ""
echo "1. Create a repository on GitHub:"
echo "   https://github.com/new"
echo ""
echo "2. Add remote origin:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/breach-ar.git"
echo ""
echo "3. Push to GitHub:"
echo "   git push -u origin main"
echo ""
echo "4. Setup GitHub Secrets:"
echo "   Go to: Settings > Secrets and variables > Actions"
echo "   Add: UNITY_LICENSE, UNITY_EMAIL, UNITY_PASSWORD"
echo ""
echo "5. Trigger a build:"
echo "   Go to: Actions > Unity Build > Run workflow"
echo ""
echo -e "${GREEN}=================================="
echo "  Setup complete! 🚀"
echo "==================================${NC}"
